Trainers2:

BillGroup:
	db "BILL@"
	db (1 << TRAINERTYPE_MOVES) | (1 << TRAINERTYPE_ITEM)
	db 100, EEVEE, LEFTOVERS
		db DOUBLE_EDGE
		db GROWTH
		db DOUBLE_TEAM
		db BATON_PASS
	db 100, JOLTEON, BURN_GUARD
		db THUNDERBOLT
		db SHADOW_BALL
		db AGILITY
		db BATON_PASS
	db 100, VAPOREON, PARLYZ_GUARD
		db SURF
		db ICE_BEAM
		db ACID_ARMOR
		db BATON_PASS
	db 100, FLAREON, POISON_GUARD
		db FLARE_BLITZ
		db SUBMISSION
		db CURSE
		db BATON_PASS
	db 100, UMBREON, FREEZE_GUARD
		db DARK_PULSE
		db SLUDGE_BOMB
		db MEAN_LOOK
		db BATON_PASS
	db 100, ESPEON, SLEEP_GUARD
		db PSYCHIC_M
		db DAZZLINGLEAM
		db GROWTH
		db BATON_PASS
	db $ff ; end

	db "BILL@"
	db (1 << TRAINERTYPE_MOVES)
	db 17, EEVEE
		db TACKLE
		db TAIL_WHIP
		db SAND_ATTACK
		db GROWL
	db 17, FLAREON
		db TACKLE
		db TAIL_WHIP
		db SAND_ATTACK
		db EMBER
	db 17, JOLTEON
		db TACKLE
		db TAIL_WHIP
		db SAND_ATTACK
		db THUNDERSHOCK
	db 17, VAPOREON
		db TACKLE
		db TAIL_WHIP
		db SAND_ATTACK
		db WATER_GUN
	db $ff ; end

ProfElmGroup:
	db "ELM@"
	db (1 << TRAINERTYPE_MOVES) | (1 << TRAINERTYPE_ITEM) | (1 << TRAINERTYPE_MAXXP)
	db 100, UNOWN, BRIGHTPOWDER
		db PSYCHIC_M
		db HIDDEN_POWER
		db ANCIENTPOWER
		db DOUBLE_TEAM
	db 100, MEGANIUM, CONFUSEGUARD
		db PETAL_DANCE
		db OUTRAGE
		db REFLECT
		db LIGHT_SCREEN
	db 100, TYPHLOSION, CHARCOAL
		db FLAMETHROWER
		db EARTHQUAKE
		db SMOKESCREEN
		db WILLOWISP
	db 100, FERALIGATR, MYSTIC_WATER
		db WATERFALL
		db CRUNCH
		db IRON_TAIL
		db ICE_PUNCH
	db 100, DONPHAN, LEFTOVERS
		db EARTHQUAKE
		db ROLLOUT
		db DEFENSE_CURL
		db FLARE_BLITZ
	db 100, TOGETIC, BRIGHTPOWDER
		db DAZZLINGLEAM
		db AIR_SLASH
		db ANCIENTPOWER
		db SOFTBOILED
	db $ff ; end

tppPcGroup:
	db "PC@"
	db (1 << TRAINERTYPE_MOVES) | (1 << TRAINERTYPE_ITEM) | (1 << TRAINERTYPE_MAXXP)
	db 100, LUGIA, LEFTOVERS
		db AEROBLAST
		db PSYCHIC_M
		db EARTHQUAKE
		db SURF
	db 100, HO_OH, QUICK_CLAW
		db SACRED_FIRE
		db THUNDER
		db EARTHQUAKE
		db GIGA_DRAIN
	db 100, MEWTWO, KINGS_ROCK
		db PSYCHIC_M
		db TRI_ATTACK
		db SUBMISSION
		db RECOVER
	db $ff

	db "PC@"
	db 0
	; This party is handled separately.
	db $ff

	db "PC@"
	db 0
	; This party is handled separately.
	db $ff

GiovanniGroup:
	db "GIOVANNI@"
	db (1 << TRAINERTYPE_MOVES) | ( 1 << TRAINERTYPE_ITEM)
	db 62, MURKROW, BLACKGLASSES
		db DARK_PULSE
		db WING_ATTACK
		db AGILITY
		db MEAN_LOOK
	db 64, RHYDON, SOFT_SAND
		db HORN_DRILL
		db ROCK_SLIDE
		db EARTHQUAKE
		db STOMP
	db 65, NIDOKING, GOLD_BERRY
		db HORN_DRILL
		db SURF
		db EARTHQUAKE
		db STOMP
	db 65, NIDOQUEEN, GOLD_BERRY
		db HORN_DRILL
		db SURF
		db EARTHQUAKE
		db STOMP
	db 64, DUGTRIO, BRIGHTPOWDER
		db FISSURE
		db MAGNITUDE
		db DIG
		db EARTHQUAKE
	db 67, KANGASKHAN, LEFTOVERS
		db BODY_SLAM
		db DOUBLE_TEAM
		db EARTHQUAKE
		db REVERSAL
	db $ff

	db "GIOVANNI@"
	db (1 << TRAINERTYPE_MOVES) | ( 1 << TRAINERTYPE_ITEM) | (1 << TRAINERTYPE_MAXXP)
	db 95, MURKROW, SCOPE_LENS
		db DARK_PULSE
		db AIR_SLASH
		db AGILITY
		db SWAGGER
	db 97, DUGTRIO, BRIGHTPOWDER
		db DIG
		db SLASH
		db SANDSTORM
		db EARTHQUAKE
	db 98, NIDOKING, KINGS_ROCK
		db POISON_JAB
		db EARTHQUAKE
		db THUNDER
		db FIRE_BLAST
	db 98, NIDOQUEEN, GOLD_BERRY
		db POISON_JAB
		db EARTHQUAKE
		db THUNDER
		db BLIZZARD
	db 97, RHYDON, HARD_STONE
		db DRILL_RUN
		db ROCK_SLIDE
		db MEGAHORN
		db EARTHQUAKE
	db 100, KANGASKHAN, LEFTOVERS
		db THRASH
		db EARTHQUAKE
		db DYNAMICPUNCH
		db FISSURE
	db $ff

CoolSiblingsGroup:
	db "ELAN&IDA@"
	db (1 << TRAINERTYPE_MOVES)
	db 71, PORYGON2
		db TRI_ATTACK
		db BLIZZARD
		db MIND_READER
		db ZAP_CANNON
	db 70, AZUMARILL
		db PLAY_ROUGH
		db BELLY_DRUM
		db DOUBLE_EDGE
		db AQUA_JET
	db $ff

	db "ELAN&IDA@"
	db (1 << TRAINERTYPE_MOVES)
	db 70, AZUMARILL
		db PLAY_ROUGH
		db BELLY_DRUM
		db DOUBLE_EDGE
		db AQUA_JET
	db 71, PORYGON2
		db TRI_ATTACK
		db BLIZZARD
		db MIND_READER
		db ZAP_CANNON
	db $ff

	db "ARA&BELLA@"
	db (1 << TRAINERTYPE_MOVES)
	db 72, STANTLER
		db ZEN_HEADBUTT
		db THRASH
		db THUNDER_WAVE
		db HI_JUMP_KICK
	db 71, TAUROS
		db OUTRAGE
		db HORN_DRILL
		db EARTHQUAKE
		db DOUBLE_EDGE
	db $ff

	db "ARA&BELLA@"
	db (1 << TRAINERTYPE_MOVES)
	db 71, TAUROS
		db OUTRAGE
		db HORN_DRILL
		db EARTHQUAKE
		db DOUBLE_EDGE
	db 72, STANTLER
		db ZEN_HEADBUTT
		db THRASH
		db THUNDER_WAVE
		db HI_JUMP_KICK
	db $ff

	db "MING&LEE@"
	db 0
	db 100, DRAGONITE
	db 100, KINGDRA
	db $ff

	db "MING&LEE@"
	db 0
	db 100, KINGDRA
	db 100, DRAGONITE
	db $ff

; ===========================
; =====================

RivalRBGroup:

	db "<GREEN>@"
	db 0
	db 5, SQUIRTLE
	db $ff

	db "<GREEN>@"
	db 0
	db 5, BULBASAUR
	db $ff

	db "<GREEN>@"
	db 0
	db 5, CHARMANDER
	db $ff

; ===============================

	db "<GREEN>@"
	db 0 ; normal
	db 3, RATTATA
	db 7, SQUIRTLE
	db $ff

	db "<GREEN>@"
	db 0 ; normal
	db 3, RATTATA
	db 7, BULBASAUR
	db $ff

	db "<GREEN>@"
	db 0 ; normal
	db 3, RATTATA
	db 7, CHARMANDER
	db $ff

; ==============================

	db "<GREEN>@"
	db (1 << TRAINERTYPE_MOVES)
	db 15, RATTATA
		db TACKLE
		db TAIL_WHIP
		db QUICK_ATTACK
		db BITE
	db 14, PIKACHU
		db THUNDERSHOCK
		db GROWL
		db TAIL_WHIP
		db QUICK_ATTACK
	db 16, SQUIRTLE
		db TACKLE
		db TAIL_WHIP
		db WITHDRAW
		db WATER_GUN
	db $ff

	db "<GREEN>@"
	db (1 << TRAINERTYPE_MOVES)
	db 15, RATTATA
		db TACKLE
		db TAIL_WHIP
		db QUICK_ATTACK
		db BITE
	db 14, PIKACHU
		db THUNDERSHOCK
		db GROWL
		db TAIL_WHIP
		db QUICK_ATTACK
	db 16, BULBASAUR
		db TACKLE
		db VINE_WHIP
		db LEECH_SEED
		db POISONPOWDER
	db $ff

	db "<GREEN>@"
	db (1 << TRAINERTYPE_MOVES)
	db 15, RATTATA
		db TACKLE
		db TAIL_WHIP
		db QUICK_ATTACK
		db BITE
	db 14, PIKACHU
		db THUNDERSHOCK
		db GROWL
		db TAIL_WHIP
		db QUICK_ATTACK
	db 16, CHARMANDER
		db SCRATCH
		db SMOKESCREEN
		db EMBER
		db METAL_CLAW
	db $ff

; ==============================

	db "<GREEN>@"
	db (1 << TRAINERTYPE_MOVES)
	db 17, RATICATE
		db CUT
		db TAIL_WHIP
		db QUICK_ATTACK
		db BITE
	db 16, PIKACHU
		db THUNDERSHOCK
		db QUICK_ATTACK
		db THUNDER_WAVE
		db DOUBLE_TEAM
	db 15, CUBONE
		db BONE_CLUB
		db GROWL
		db TAIL_WHIP
		db HEADBUTT
	db 18, WARTORTLE
		db BUBBLE
		db WITHDRAW
		db WATER_GUN
		db BITE
	db $ff

	db "<GREEN>@"
	db (1 << TRAINERTYPE_MOVES)
	db 17, RATICATE
		db CUT
		db TAIL_WHIP
		db QUICK_ATTACK
		db BITE
	db 16, PIKACHU
		db THUNDERSHOCK
		db QUICK_ATTACK
		db THUNDER_WAVE
		db DOUBLE_TEAM
	db 15, CUBONE
		db BONE_CLUB
		db GROWL
		db TAIL_WHIP
		db HEADBUTT
	db 18, IVYSAUR
		db VINE_WHIP
		db LEECH_SEED
		db POISONPOWDER
		db SLEEP_POWDER
	db $ff

	db "<GREEN>@"
	db (1 << TRAINERTYPE_MOVES)
	db 17, RATICATE
		db CUT
		db TAIL_WHIP
		db QUICK_ATTACK
		db BITE
	db 16, PIKACHU
		db THUNDERSHOCK
		db QUICK_ATTACK
		db THUNDER_WAVE
		db DOUBLE_TEAM
	db 15, CUBONE
		db BONE_CLUB
		db GROWL
		db TAIL_WHIP
		db HEADBUTT
	db 18, CHARMELEON
		db EMBER
		db METAL_CLAW
		db SMOKESCREEN
		db RAGE
	db $ff

; ================================

	db "<GREEN>@"
	db (1 << TRAINERTYPE_MOVES) | (1 << TRAINERTYPE_ITEM) | (1 << TRAINERTYPE_MAXXP)
	db 61, PIDGEOT, POWER_HERB
		db SKY_ATTACK
		db DOUBLE_EDGE
		db HEAT_WAVE
		db WHIRLWIND
	db 61, RAICHU, GOLD_BERRY
		db THUNDERBOLT
		db IRON_TAIL
		db SURF
		db WILD_CHARGE
	db 61, MAROWAK, THICK_CLUB
		db BONEMERANG
		db ROCK_SLIDE
		db PERISH_SONG
		db EARTHQUAKE
	db 61, NINETALES, CHARCOAL
		db FLAMETHROWER
		db PSYCHIC_M
		db SHADOW_BALL
		db WILLOWISP
	db 61, VICTREEBEL, MIRACLE_SEED
		db GIGA_DRAIN
		db SLUDGE_BOMB
		db SLEEP_POWDER
		db REFLECT
	db 65, BLASTOISE, LEFTOVERS
		db HYDRO_PUMP
		db FLASH_CANNON
		db ICE_BEAM
		db ZAP_CANNON
	db $ff

	db "<GREEN>@"
	db (1 << TRAINERTYPE_MOVES) | (1 << TRAINERTYPE_ITEM) | (1 << TRAINERTYPE_MAXXP)
	db 61, PIDGEOT, POWER_HERB
		db SKY_ATTACK
		db DOUBLE_EDGE
		db HEAT_WAVE
		db WHIRLWIND
	db 61, RAICHU, GOLD_BERRY
		db THUNDERBOLT
		db IRON_TAIL
		db SURF
		db WILD_CHARGE
	db 61, MAROWAK, THICK_CLUB
		db BONEMERANG
		db ROCK_SLIDE
		db PERISH_SONG
		db EARTHQUAKE
	db 61, STARMIE, MYSTIC_WATER
		db SURF
		db PSYCHIC_M
		db ICE_BEAM
		db THUNDER
	db 61, NINETALES, CHARCOAL
		db FLAMETHROWER
		db PSYCHIC_M
		db SHADOW_BALL
		db WILLOWISP
	db 65, VENUSAUR, LEFTOVERS
		db GIGA_DRAIN
		db SLUDGE_BOMB
		db SLEEP_POWDER
		db LEECH_SEED
	db $ff

	db "<GREEN>@"
	db (1 << TRAINERTYPE_MOVES) | (1 << TRAINERTYPE_ITEM) | (1 << TRAINERTYPE_MAXXP)
	db 61, PIDGEOT, POWER_HERB
		db SKY_ATTACK
		db DOUBLE_EDGE
		db HEAT_WAVE
		db WHIRLWIND
	db 61, RAICHU, GOLD_BERRY
		db THUNDERBOLT
		db IRON_TAIL
		db SURF
		db WILD_CHARGE
	db 61, MAROWAK, THICK_CLUB
		db BONEMERANG
		db ROCK_SLIDE
		db PERISH_SONG
		db EARTHQUAKE
	db 61, VICTREEBEL, MIRACLE_SEED
		db GIGA_DRAIN
		db SLUDGE_BOMB
		db SLEEP_POWDER
		db REFLECT
	db 61, STARMIE, MYSTIC_WATER
		db SURF
		db PSYCHIC_M
		db ICE_BEAM
		db THUNDER
	db 65, CHARIZARD, LEFTOVERS
		db FIRE_BLAST
		db AIR_SLASH
		db EARTHQUAKE
		db WILLOWISP
	db $ff

; ==============================

	db "<GREEN>@"
	db (1 << TRAINERTYPE_MOVES) | (1 << TRAINERTYPE_ITEM) | (1 << TRAINERTYPE_MAXXP)
	db 100, ARTICUNO, LEFTOVERS
		db ICE_BEAM
		db BUBBLEBEAM
		db HIDDEN_POWER
		db REFLECT
	db 100, ZAPDOS, LEFTOVERS
		db THUNDERBOLT
		db DRILL_PECK
		db HIDDEN_POWER
		db THUNDER_WAVE
	db 100, MOLTRES, LEFTOVERS
		db FLAMETHROWER
		db DOUBLE_EDGE
		db HIDDEN_POWER
		db FIRE_BLAST
	db 100, SNORLAX, LEFTOVERS
		db BODY_SLAM
		db EARTHQUAKE
		db CURSE
		db REST
	db 100, LAPRAS, LEFTOVERS
		db SURF
		db ICE_BEAM
		db THUNDERBOLT
		db CONFUSE_RAY
	db 100, MEW, LEFTOVERS
		db PSYCHIC_M
		db EARTHQUAKE
		db ICE_BEAM
		db SOFTBOILED
	db $ff

BrockRBGroup:
	db "BROCK@" ; easy
	db (1 << TRAINERTYPE_MOVES)
	db 8, GEODUDE
		db TACKLE
		db DEFENSE_CURL
		db ROLLOUT
		db SANDSTORM
	db 10, ONIX
		db BIDE
		db WRAP
		db IRON_TAIL
		db SANDSTORM
	db $ff ; end

	db "BROCK@" ; normal
	db (1 << TRAINERTYPE_MOVES)
	db 10, GEODUDE
		db TACKLE
		db DEFENSE_CURL
		db ROLLOUT
		db SANDSTORM
	db 12, ONIX
		db BIDE
		db WRAP
		db IRON_TAIL
		db SANDSTORM
	db $ff ; end

MistyRBGroup:
	db "MISTY@"
	db (1 << TRAINERTYPE_MOVES)
	db 15, STARYU
		db SWIFT
		db RAIN_DANCE
		db RAPID_SPIN
		db BUBBLE
	db 18, STARMIE
		db BUBBLEBEAM
		db CONFUSION
		db SWIFT
		db HARDEN
	db $ff ; end

BabaGroup:
	db "KRIS@"
	db (1 << TRAINERTYPE_MOVES) | (1 << TRAINERTYPE_ITEM) | (1 << TRAINERTYPE_MAXXP)
	db 100, RAIKOU, LEFTOVERS
		db THUNDERBOLT
		db CRUNCH
		db IRON_HEAD
		db HIDDEN_POWER ; ICE
	db 100, ENTEI, LEFTOVERS
		db FIRE_BLAST
		db CRUNCH
		db IRON_HEAD
		db HIDDEN_POWER ; GROUND
	db 100, SUICUNE, LEFTOVERS
		db SURF
		db ICE_BEAM
		db ROAR
		db HIDDEN_POWER ; GRASS
	db 100, CELEBI, LEFTOVERS
		db PSYCHIC_M
		db GIGA_DRAIN
		db RECOVER
		db LEECH_SEED
	db 100, LUGIA, LEFTOVERS
		db AEROBLAST
		db PSYCHIC_M
		db EARTHQUAKE
		db SURF
	db 100, HO_OH, LEFTOVERS
		db SACRED_FIRE
		db THUNDER
		db EARTHQUAKE
		db GIGA_DRAIN
	db $ff

ExecutiveEgkGroup:
	db "EXECUTIVE@"
	db (1 << TRAINERTYPE_ITEM)
	db 15, RATICATE, BERSERK_GENE
	db $ff
